---
dev:
  streamArn: 'arn:aws:kinesis:us-west-2:example:stream/usage-dev'
staging:
  streamArn:
    'Fn::ImportValue': 'some-other-service:${self:provider.stage}:StreamARN'
production:
  streamArn:
    'Fn::ImportValue': 'some-other-service:${self:provider.stage}:StreamARN'
